on: push
name: Build
jobs:
  test:
    name: build
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build and test
        run: swift test
